package model.services;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.services.common.AppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 23 15:30:50 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxOdmIssueToStitchHTVO1.
     * @return XxOdmIssueToStitchHTVO1
     */
    public ViewObjectImpl getXxOdmIssueToStitchHTVO1() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToStitchHTVO1");
    }

    /**
     * Container's getter for XxOdmIssueToStitchLTVO1.
     * @return XxOdmIssueToStitchLTVO1
     */
    public ViewObjectImpl getXxOdmIssueToStitchLTVO1() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToStitchLTVO1");
    }

    /**
     * Container's getter for XxOdmIssueToStitchLTVO2.
     * @return XxOdmIssueToStitchLTVO2
     */
    public ViewObjectImpl getXxOdmIssueToStitchLTVO2() {
        return (ViewObjectImpl)findViewObject("XxOdmIssueToStitchLTVO2");
    }

    /**
     * Container's getter for XxOdmStitchingUkLink1.
     * @return XxOdmStitchingUkLink1
     */
    public ViewLinkImpl getXxOdmStitchingUkLink1() {
        return (ViewLinkImpl)findViewLink("XxOdmStitchingUkLink1");
    }
    
    
    
    
    
    /**
            * Method to set page parameter value 
            * */

        public void setSessionValues(String orgId, String userId, String respId,
                                     String respAppl) {

            System.out.println("UserId....." + userId);
            System.out.println("OrgID..." + orgId);

            


            if (userId != null) {
                FacesContext fctx = FacesContext.getCurrentInstance();
                ExternalContext ectx = fctx.getExternalContext();
                HttpSession userSession = (HttpSession)ectx.getSession(false);
                userSession.setAttribute("userId", userId);
                 
                userSession.setAttribute("orgId", orgId);
                userSession.setAttribute("respId",respId);//respId
        
                
                
           
            }
        }


    /**
     * Container's getter for ViewObj1.
     * @return ViewObj1
     */
    public ViewObjectImpl getViewObj1() {
        return (ViewObjectImpl)findViewObject("ViewObj1");
    }
}
